language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    #     Laravel 7.*
    - php: 7.3
      env: LARAVEL='7.*'
    - php: 7.4
      env: LARAVEL='7.*'
    - php: 8.0
      env: LARAVEL='7.*'
    #     Laravel 8.*
    - php: 7.3
      env: LARAVEL='8.*'
    - php: 7.4
      env: LARAVEL='8.*'
    - php: 8.0
      env: LARAVEL='8.*'

before_install:
  - travis_retry composer self-update
  - travis_retry composer require --no-update --no-interaction "illuminate/container:${LARAVEL}" "illuminate/cache:${LARAVEL}"

install:
  - travis_retry composer update --prefer-dist --no-interaction --no-suggest
  - travis_retry composer du -o

before_script:
  - phpenv config-rm xdebug.ini || return 0

script:
  - vendor/bin/phpunit
  - vendor/bin/phpstan analyze src config --level max